#!/usr/bin/env python

Import("env")

import os
from platform_methods import run_in_subprocess

common_t = [
    "main.c",
]

prog = env.add_program("#bin/prog", common_t, PROGSUFFIX=env["PROGSUFFIX"])
