#!/usr/bin/env python

Import("env")

from platform_methods import run_in_subprocess

env.core_sources = []

# Chain load SCsubs
#SConscript("os/SCsub")
SConscript("math/SCsub")
#SConscript("crypto/SCsub")
#SConscript("io/SCsub")
#SConscript("bind/SCsub")


# Build it all as a library
lib = env.add_library("core", env.core_sources)
env.Prepend(LIBS=[lib])

